/**
 * generated by Xtext 2.12.0
 */
package mcgill.xtext.turn;

import mcgill.xtext.turn.CommonValueConverter;
import mcgill.xtext.turn.MyQNP;
import org.eclipse.xtext.conversion.IValueConverterService;
import org.eclipse.xtext.naming.IQualifiedNameProvider;
import org.xtext.example.mydsl.AbstractTURNRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class TURNRuntimeModule extends AbstractTURNRuntimeModule {
  @Override
  public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {
    return MyQNP.class;
  }
  
  @Override
  public Class<? extends IValueConverterService> bindIValueConverterService() {
    return CommonValueConverter.class;
  }
}
